spring:
  config:
    activate:
      on-profile: "qa"


build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA API'S"
  contactDetails:
    name: "Cherryl Pankaj -QA Lead"
    email: "Cherryl@eazyBank.com"
  onCallSupport:
    -(310)2876-4376
    -(231)234-1267