spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"


loans:
  message: "Welcome to EazyBank Loans related prod API'S"
  contactDetails:
    name: "Pelias Sudhir -Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    -(723) 656-8709
    -(156)342-0956